project:
  type: website

website:
  title: "Catchment Evidence Pack"
  navbar:
    background: "#008531"
    left:
      - href: index.qmd
        text: Home
      - href: Overview.qmd
        text: Overview
      - href: Ecology.qmd
        text: Ecology
      - href: Physical_Habitat.qmd
        text: Physical Habitat
      - href: Water_Quality.qmd
        text: Water Quality
      - href: Water_Resources.qmd
        text: Water Resources
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Environment Agency"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


