project:
  type: website

website:
  title: "CEP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Ecology.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



