project:
  type: website

website:
  title: "Catchment Evidence Pack"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Overview.qmd
      - Ecology.qmd
      - Physical_Habitat.qmd
      - Water_Quality.qmd
      
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



