project:
  type: website

website:
  title: "Catchment Evidence Pack"
  navbar:
    background: "#008531"
    left:
      - href: index.qmd
        text: Home
      - Overview.qmd
      - Ecology.qmd
      - Physical_Habitat.qmd
      - Water_Quality.qmd
      - Water_Resources.qmd
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, H Gray"
    
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



